#!/bin/sh

templates=$(dirname $0)/templates

infrastructure=$1

shift

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] && \
    [ "$infrastructure" != "openstack" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|warden|vsphere|openstack> [stubs...]"
  exit 1
fi

spiff merge \
  $templates/cf-mysql-template.yml \
  $templates/cf-infrastructure-${infrastructure}.yml \
  $*
