#!/bin/bash

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

templates="${MY_DIR}/templates"

infrastructure="$1"

if [ "$infrastructure" != "aws" ] && \
    [ "$infrastructure" != "warden" ] && \
    [ "$infrastructure" != "vsphere" ] ; then
  echo "usage: ./generate_deployment_manifest <aws|warden|vsphere> [stubs...]"
  exit 1
fi

shift

spiff merge \
  "$templates/cf-mysql-template.yml" \
  "$templates/cf-infrastructure-${infrastructure}.yml" \
  $*
