---
name: cf-warden-mysql
director_uuid: PLACEHOLDER-DIRECTOR-UUID
releases:
  - name: cf
    version: latest

jobs:
  - instances: 1
    name: mysql
    properties:
      admin_password: password
  - instances: 1
    name: cf-mysql-broker
    properties:
      auth_password: password
      auth_username: admin
      cookie_secret: 94046872-2602-4ca6-8d07-8b0da9762477
      cc_api_uri: http://api.10.244.0.34.xip.io
      services:
      - name: p-mysql
        dashboard_client:
          secret: p-mysql-secret

meta:
  redirect_uri: http://10.244.1.130
