#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

export CF_API_USER="admin"
export CF_API_PASSWORD="admin"
export PROXY_API_USER="username"
export PROXY_API_PASSWORD="password"
export USE_SMALL_PLANS=true
export USE_HTTPS=false

DOMAIN="${DOMAIN:-10.244.0.34}"
# If a file exists with an api-address, use that instead
if [ -f ${WORKSPACE_DIR}/api-address ]; then
  API_ADDRESS=$( cat ${WORKSPACE_DIR}/api-address )
  echo -e "WARNING: Found API address file at ${INFO_COLOR}${WORKSPACE_DIR}/api-address${NO_COLOR} - using ${INFO_COLOR}${API_ADDRESS}${NO_COLOR} instead of ${INFO_COLOR}${DOMAIN}${NO_COLOR}"
  export DOMAIN=${API_ADDRESS}
fi
export DOMAIN="${DOMAIN}.xip.io"

${RELEASE_DIR}/scripts/create_integration_test_config