#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

export CF_API_USER="admin"
export CF_API_PASSWORD="admin"
export PROXY_API_USER="username"
export PROXY_API_PASSWORD="password"
export USE_SMALL_PLANS=true
export USE_HTTPS=false

BOSH_LITE_PRIVATE_IP_FILE="${BOSH_LITE_PRIVATE_IP_FILE:-}"
if [ ! -z "${BOSH_LITE_PRIVATE_IP_FILE}" ]; then
  DOMAIN=$(cat "${BOSH_LITE_PRIVATE_IP_FILE}" | jq -r '.private_ip' )
  DOMAIN="${DOMAIN}.xip.io"
fi
export DOMAIN="${DOMAIN:-bosh-lite.com}"

${RELEASE_DIR}/scripts/create_integration_test_config
