#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )

# Use make-manifest script to handle targetting and logging in to the director
${MY_DIR}/make_manifest

function assert_rebase_attempted_without_changes() {
  ACCEPTABLE_ERROR_SEARCH_RESULT=$(echo $REBASE_OUTPUT | grep -i rebase.*attempted.*without.*changes)
  if [ $ACCEPTABLE_ERROR_SEARCH_RESULT -ne 0 ]; then
    echo "Failed to upload release"
    exit 1
  fi
}

pushd ${RELEASE_DIR}
    bosh create release --force --name cf-mysql
    REBASE_OUTPUT=$(bosh -n upload release --rebase) || assert_rebase_attempted_without_changes
popd
