#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

CONFIG_LOCATION=${CONFIG_LOCATION:-${RELEASE_DIR}/integration-config.json}
echo -e "Creating config file at ${INFO_COLOR}${CONFIG_LOCATION}${NO_COLOR}..."

DOMAIN=${DOMAIN:-10.244.0.34}

# If a file exists with an api-address, use that instead
if [ -f ${WORKSPACE_DIR}/api-address ]; then
  API_ADDRESS=$( cat ${WORKSPACE_DIR}/api-address )
  echo -e "WARNING: Found API address file at ${INFO_COLOR}${WORKSPACE_DIR}/api-address${NO_COLOR} - using ${INFO_COLOR}${API_ADDRESS}${NO_COLOR} instead of ${INFO_COLOR}${DOMAIN}${NO_COLOR}"
  DOMAIN=${API_ADDRESS}
fi

cat > ${CONFIG_LOCATION} <<EOF
{
  "api": "http://api.${DOMAIN}.xip.io",
  "apps_domain": "${DOMAIN}.xip.io",
  "admin_user": "admin",
  "admin_password": "admin",
  "broker_host": "p-mysql.${DOMAIN}.xip.io",
  "service_name": "p-mysql",
  "plans" : [
    {
      "plan_name": "100mb",
      "max_user_connections": 20,
      "max_storage_mb": 10
    },
    {
      "plan_name": "1gb",
      "max_user_connections": 40,
      "max_storage_mb": 20
    }
  ],
  "skip_ssl_validation": true,
  "timeout_scale": 1.0,
  "proxy": {
    "external_host":"p-mysql.${DOMAIN}.xip.io",
    "api_username":"username",
    "api_password":"password",
    "api_force_https": true,
    "skip_ssl_validation": true
  }
}
EOF

echo -e "${OK_COLOR}OK${NO_COLOR}"

echo -e "
TIP: Export the environment variable with the following command:

${ACTION_COLOR}export CONFIG=${CONFIG_LOCATION}${NO_COLOR}"
