#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

DEPLOYMENT_NAME="cf-warden-mysql"
BOSH_LITE_IP=192.168.50.4

# If a file exists with an api-address, use that instead
if [ -f ${WORKSPACE_DIR}/api-address ]; then
  BOSH_LITE_IP=$( cat ${WORKSPACE_DIR}/api-address )
fi

export BOSH_USER=admin
export BOSH_PASSWORD=admin
export BOSH_RELEASES_DIR=${WORKSPACE_DIR}

bosh -n target ${BOSH_LITE_IP}

DEPLOYMENTS_OUTPUT=$( bosh deployments )

set +e
echo ${DEPLOYMENTS_OUTPUT} | grep ${DEPLOYMENT_NAME}
DEPLOYMENT_GREP_RESULT=$?
set -e

# A value of 0 indicates grep matched successfully,
# and hence the deployment exists and we should delete it.
if [ ${DEPLOYMENT_GREP_RESULT} -eq 0 ]; then
  bosh -n delete deployment ${DEPLOYMENT_NAME} --force
else
  echo "deployment ${DEPLOYMENT_NAME} not found - nothing to delete"
fi
