#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OUTPUT_FILE=${OUTPUT_FILE:?}
NODE_COUNT=${NODE_COUNT:-3}

# select stub that corresponds to $NODE_COUNT
MYSQL_STUB="${RELEASE_DIR}/bosh-lite/cf-mysql-stub-spiff-${NODE_COUNT}-node.yml"
if [[ ! -f "${MYSQL_STUB}" ]] ; then
  echo "Can't find ${MYSQL_STUB}"
  exit 1
fi

# concourse bosh resource will automatically replace the UUID
MYSQL_STUB_MODIFIED=/tmp/mysql-stub.yml
sed 's/PLACEHOLDER-DIRECTOR-UUID/~/' ${MYSQL_STUB} > ${MYSQL_STUB_MODIFIED}

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
  ${MYSQL_STUB_MODIFIED} \
  "$@" > ${WORKSPACE_DIR}/${OUTPUT_FILE}