#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OUTPUT_FILE=${OUTPUT_FILE:?}
NODE_COUNT=${NODE_COUNT:-3}
BOSH_LITE_PRIVATE_IP=$(cat "${BOSH_LITE_PRIVATE_IP_FILE:?}" | jq -r '.private_ip' )
USE_PREVIOUS_RELEASE=${USE_PREVIOUS_RELEASE:-false}

get_version() {
  if [ "${USE_PREVIOUS_RELEASE}" = true ]; then
  echo "$(find ${RELEASE_DIR}/releases/cf-mysql-* -type f -printf "%f\n" | \
    cut -d '-' -f3              | \
    cut -d '.' -f1              | \
    sort -n                     | \
    tail -1)"
  else
    echo "latest"
  fi
}

# select stub that corresponds to $NODE_COUNT
MYSQL_STUB="${RELEASE_DIR}/bosh-lite/cf-mysql-stub-spiff-${NODE_COUNT}-node.yml"
if [[ ! -f "${MYSQL_STUB}" ]] ; then
  echo "Can't find ${MYSQL_STUB}"
  exit 1
fi

# concourse bosh resource will automatically replace the UUID
MYSQL_STUB_MODIFIED=/tmp/mysql-stub.yml
sed 's/PLACEHOLDER-DIRECTOR-UUID/~/' ${MYSQL_STUB} > ${MYSQL_STUB_MODIFIED}

MYSQL_STUB_CF_PRIVATE_IP=/tmp/private-ip-stub.yml
cat <<PRIVATE_IP_STUB > ${MYSQL_STUB_CF_PRIVATE_IP}
properties:
  domain: ${BOSH_LITE_PRIVATE_IP}.xip.io
  system_domain: ${BOSH_LITE_PRIVATE_IP}.xip.io
  app_domains:
  - ${BOSH_LITE_PRIVATE_IP}.xip.io
PRIVATE_IP_STUB

MYSQL_VERSION="$(get_version)"
VERSION_STUB=/tmp/version-stub.yml
cat <<VERSION_STUB > ${VERSION_STUB}
releases:
- name: cf-mysql
  version: ${MYSQL_VERSION}
VERSION_STUB

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
  ${MYSQL_STUB_MODIFIED} \
  ${MYSQL_STUB_CF_PRIVATE_IP} \
  ${VERSION_STUB} \
  "$@" > ${WORKSPACE_DIR}/${OUTPUT_FILE}
