#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )

# And that the release directory lives one directory below the workspace directory.
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

BOSH_LITE_USERNAME=${BOSH_LITE_USERNAME:-admin}
BOSH_LITE_PASSWORD=${BOSH_LITE_PASSWORD:-admin}

# By default use 3 node stub
mysql_stub="cf-mysql-stub-spiff-3-node.yml"
# If any arguments were provided,
# see if there is a stub with the number of nodes provided.
# If not, assume the argument is not the number of nodes and continue.
if [[ $# -ne 0 ]] && [[ -f "${RELEASE_DIR}/bosh-lite/cf-mysql-stub-spiff-$1-node.yml" ]] ; then
  mysql_stub="cf-mysql-stub-spiff-$1-node.yml"
  echo -e "Using stub ${INFO_COLOR}${RELEASE_DIR}/bosh-lite/${mysql_stub}${NO_COLOR}"
  shift
fi

mkdir -p ${RELEASE_DIR}/bosh-lite/tmp
mkdir -p ${RELEASE_DIR}/bosh-lite/manifest

cp \
  ${RELEASE_DIR}/bosh-lite/$mysql_stub \
  ${RELEASE_DIR}/bosh-lite/tmp/cf-mysql-stub-with-uuid.yml

DIRECTOR_IP=${DIRECTOR_IP:-192.168.50.4}

# If a file exists with an api-address, use that instead
if [ -f ${WORKSPACE_DIR}/api-address ]; then
  API_ADDRESS=$( cat ${WORKSPACE_DIR}/api-address )
  echo -e "WARNING: Found API address file at ${INFO_COLOR}${WORKSPACE_DIR}/api-address${NO_COLOR}
    - using ${INFO_COLOR}${API_ADDRESS}${NO_COLOR} instead of ${INFO_COLOR}${DIRECTOR_IP}${NO_COLOR} for director IP
    - and ${INFO_COLOR}${API_ADDRESS}.xip.io${NO_COLOR} instead of ${INFO_COLOR}bosh-lite.com${NO_COLOR} for API address"
  DIRECTOR_IP=${API_ADDRESS}
  perl -pi -e "s/bosh-lite.com/${API_ADDRESS}.xip.io/g" $RELEASE_DIR/bosh-lite/tmp/cf-mysql-stub-with-uuid.yml
fi

bosh -n target ${DIRECTOR_IP}
bosh -n login "${BOSH_LITE_USERNAME}" "${BOSH_LITE_PASSWORD}"
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" $RELEASE_DIR/bosh-lite/tmp/cf-mysql-stub-with-uuid.yml

${RELEASE_DIR}/generate_deployment_manifest \
  warden \
  ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
  ${RELEASE_DIR}/bosh-lite/tmp/cf-mysql-stub-with-uuid.yml \
  "$@" > ${RELEASE_DIR}/bosh-lite/manifests/cf-mysql-manifest.yml

bosh deployment $RELEASE_DIR/bosh-lite/manifests/cf-mysql-manifest.yml
