#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
MYSQL_RELEASE_DIR=${MYSQL_RELEASE_DIR:-$BOSH_RELEASES_DIR/cf-mysql-release}

if [[ ! -d $MYSQL_RELEASE_DIR ]]; then
  echo "Cannot find cf-mysql-release at $MYSQL_RELEASE_DIR; override with \$MYSQL_RELEASE_DIR variable"
  exit 1
fi

cd $MYSQL_RELEASE_DIR
mkdir -p bosh-lite/tmp
mkdir -p bosh-lite/manifests
cp bosh-lite/cf-mysql-stub-spiff.yml bosh-lite/tmp/cf-mysql-stub-with-uuid.yml
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" bosh-lite/tmp/cf-mysql-stub-with-uuid.yml

bosh target https://192.168.50.4:25555
$MYSQL_RELEASE_DIR/generate_deployment_manifest warden bosh-lite/tmp/cf-mysql-stub-with-uuid.yml > bosh-lite/manifests/cf-mysql-manifest.yml
bosh deployment bosh-lite/manifests/cf-mysql-manifest.yml

