---
name: cf-warden-mysql
director_uuid: PLACEHOLDER-DIRECTOR-UUID
releases:
  - name: cf-mysql
    version: latest

properties:
  domain: (( merge || "" ))

jobs:
  - name: mysql_z1
    instances: 1
    networks:
    - name: mysql1
      static_ips:
      - 10.244.7.2
    properties:
      <<: (( merge || nil ))
      admin_password: password
      cluster_ips: (( jobs.mysql_z1.networks.[0].static_ips ))
  - name: mysql_z2
    instances: 1
  - name: mysql_z3
    instances: 1
  - name: cf-mysql-broker_z1
    instances: 0
  - name: cf-mysql-broker_z2
    instances: 0
  - name: proxy_z1
    properties:
      <<: (( merge || nil ))
      proxy:
        <<: (( merge || nil ))
        api_username: username
        api_password: password
  - name: proxy_z2
    instances: 1
  - name: acceptance-tests
    properties:
      no_cf: true
