#!/bin/bash

set -ex

DOCKER_IMAGE=${DOCKER_IMAGE:-cloudfoundry/cf-mysql-ci}

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives two directories below the release directory.
RELEASE_DIR="$( cd $MY_DIR/../.. && pwd )"

$MY_DIR/with_docker_cleanup docker run --privileged \
  -v $RELEASE_DIR:/workspace/cf-mysql-release \
  -w "/workspace/cf-mysql-release" \
  $DOCKER_IMAGE $@
