#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the release directory.
RELEASE_DIR=$( cd $MY_DIR/../.. && pwd )

pushd $RELEASE_DIR
        source .envrc

        ./scripts/test_submodules "$@"
popd
