#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/../.. && pwd )

export CONFIG_LOCATION="${RELEASE_DIR}/integration_config.json"
${RELEASE_DIR}/bosh-lite/create_integration_test_config
export CONFIG=${CONFIG_LOCATION}
cat ${CONFIG}

set +e
# GoCD does not print color, so do not attempt to do so
${RELEASE_DIR}/scripts/test-dashboard --noColor "$@"
return_code=$?
set -e

rm -rf ${CONFIG_LOCATION}

exit ${return_code}
