name: cf-mysql

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: cf-mysql
  version: latest

update:
  canaries: 1
  canary_watch_time: 10000-600000
  update_watch_time: 10000-600000
  max_in_flight: 1
  serial: true

instance_groups:
- name: mysql
  instances: 2
  azs: [z1, z2]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - {release: cf-mysql, name: mysql}
  migrated_from:
  - {name: mysql_z1, az: z1}
  - {name: mysql_z2, az: z2}

- name: arbitrator
  instances: 1
  azs: [z3]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: arbitrator}
  migrated_from:
  - {name: arbitrator_z3, az: z3}

- name: proxy
  instances: 2
  azs: [z1, z2]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: proxy}
  properties:
    cf_mysql:
      standalone: true
  migrated_from:
  - {name: proxy_z1, az: z1}
  - {name: proxy_z2, az: z2}

- name: bootstrap
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: bootstrap}

- name: rejoin-unsafe
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: rejoin-unsafe}

- name: verify-cluster-schemas
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: verify-cluster-schemas}

- name: smoke-tests
  instances: 1
  lifecycle: errand
  azs: [z1]
  networks: [{name: default}]
  vm_type: default
  stemcell: default
  jobs:
  - {release: cf-mysql, name: smoke-tests}
  properties:
    cf_mysql:
      smoke_tests:
        standalone_tests_only: true

properties:
  cf_mysql:
    mysql:
      admin_password: ((cf_mysql_mysql_admin_password))
      cluster_health:
        password: ((cf_mysql_mysql_cluster_health_password))
      galera_healthcheck:
        db_password: ((cf_mysql_mysql_galera_healthcheck_db_password))
        endpoint_password: ((cf_mysql_mysql_galera_healthcheck_endpoint_password))
        endpoint_username: galera-healthcheck
      persistent_disk: 100000
      roadmin_password: ((cf_mysql_mysql_roadmin_password))
    proxy:
      api_password: ((cf_mysql_proxy_api_password))

variables:
- name: cf_mysql_mysql_admin_password
  type: password
- name: cf_mysql_mysql_cluster_health_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_db_password
  type: password
- name: cf_mysql_mysql_galera_healthcheck_endpoint_password
  type: password
- name: cf_mysql_mysql_roadmin_password
  type: password
- name: cf_mysql_proxy_api_password
  type: password