---
packages:
- name: acceptance-tests
  version: !binary |-
    N2U0YWFkYTI3ODY0Yjc0ZTdhNTRhYjNkZmY0ODZkNmMxYjQzNWU1Mg==
  sha1: !binary |-
    Y2NiZjdjNDJiYjFmYjJlNTEwZjBhOTU2ZDM4NGNiZGFjM2RhZjI3NA==
  fingerprint: !binary |-
    N2U0YWFkYTI3ODY0Yjc0ZTdhNTRhYjNkZmY0ODZkNmMxYjQzNWU1Mg==
  dependencies:
  - golang
  - cli
- name: boost
  version: !binary |-
    M2ViOGJkYjFhYmI3ZWZmNWI2M2M0YzViZGI0MWMwYTc3ODkyNWMzMQ==
  sha1: !binary |-
    OTA0ZjkwNTQzZjljMmEwOTE3NWQ5M2U4ODE1MjkzNmU3OGQwM2U4MA==
  fingerprint: !binary |-
    M2ViOGJkYjFhYmI3ZWZmNWI2M2M0YzViZGI0MWMwYTc3ODkyNWMzMQ==
  dependencies: []
- name: broker-registrar
  version: !binary |-
    NTUyOGNhN2Y3OWEwMGNmZWVhYjcwYmI5OGM3OTE0Y2QzYWI3MjU5Ng==
  sha1: !binary |-
    OWEzMmVhNzdlZGU0NzIwYTI5YTFkNWZhMjA1ODJiNTM1ZjU0MzU2YQ==
  fingerprint: !binary |-
    NTUyOGNhN2Y3OWEwMGNmZWVhYjcwYmI5OGM3OTE0Y2QzYWI3MjU5Ng==
  dependencies:
  - ruby
- name: cf-mysql-broker
  version: !binary |-
    NWQzZmQ1YmNkYWY1ZTFlMzNjZTI5NzI5YTY5NmRkNjFmOWE0NWNmNw==
  sha1: !binary |-
    Y2RhMzA3YmI5ZjAzNGNmNWYyZjgyYjkxOTVhZDc2MDBmMWE3Y2M5Yg==
  fingerprint: !binary |-
    NWQzZmQ1YmNkYWY1ZTFlMzNjZTI5NzI5YTY5NmRkNjFmOWE0NWNmNw==
  dependencies:
  - ruby
  - mysqlclient
- name: check
  version: !binary |-
    ZDY4MTFmMjVlOWQ1NjQyOGE5Yjk0MjYzMWMyN2M5YjI0ZjUwNjRkYw==
  sha1: !binary |-
    ZGI4MjhjM2Y3MmY4NWI5OGI1YWZkNTExYjE2MjdiNmY0ZmUxNmQyYw==
  fingerprint: !binary |-
    ZDY4MTFmMjVlOWQ1NjQyOGE5Yjk0MjYzMWMyN2M5YjI0ZjUwNjRkYw==
  dependencies: []
- name: cli
  version: 4bb5c60db940b97d34d4a916497f9c6c558be14f
  sha1: !binary |-
    NjZiMTk3YTE4YWI0MDBlMmU3OWRkYjc1Y2UxNTQ5NWMyZjRmOGY2Ng==
  fingerprint: !binary |-
    NGJiNWM2MGRiOTQwYjk3ZDM0ZDRhOTE2NDk3ZjljNmM1NThiZTE0Zg==
  dependencies: []
- name: common
  version: ba480a46c4b2aa9484fb24ed01a8649453573e6f
  sha1: !binary |-
    YTFhOGUxNGM5OWJmYjhmZDgwZWQyMDdjZDc0MzUxODU0YzY2NjA1Yw==
  fingerprint: !binary |-
    YmE0ODBhNDZjNGIyYWE5NDg0ZmIyNGVkMDFhODY0OTQ1MzU3M2U2Zg==
  dependencies: []
- name: galera
  version: !binary |-
    M2JjNDc4MGVkYjRjNDRlNTNjMTI0Y2E1ZTA1NWRmMmU2YWVlYTg0MA==
  sha1: !binary |-
    NWJlYjlmY2JmOWM4OWIzYjY2ZWJiYzJlYjc5ODMwZjk4MjI1NTE4MA==
  fingerprint: !binary |-
    M2JjNDc4MGVkYjRjNDRlNTNjMTI0Y2E1ZTA1NWRmMmU2YWVlYTg0MA==
  dependencies:
  - scons
  - boost
  - check
- name: galera-healthcheck
  version: !binary |-
    Nzk0NGJkYTkzZDU3ZTk5Mjk4YmE5YzZlZmYxMDBlYWNhODhjMWY2MA==
  sha1: !binary |-
    N2M2M2RkOTRmNmMyZTdhOTUyYzA5ZTFlMmQxZmFjYmNhOGIwOGJlZg==
  fingerprint: !binary |-
    Nzk0NGJkYTkzZDU3ZTk5Mjk4YmE5YzZlZmYxMDBlYWNhODhjMWY2MA==
  dependencies:
  - golang
- name: golang
  version: !binary |-
    YWE1ZjkwZjA2YWRhMzc2MDg1NDE0YmZjMGM1NmM4Y2Q2N2FiYmE5Yw==
  sha1: !binary |-
    OGUwYjM5NTU3ZDg1OTY2NmJiMTI5Y2RkMjgyMmY3MmE3ZDU5MjMzOA==
  fingerprint: !binary |-
    YWE1ZjkwZjA2YWRhMzc2MDg1NDE0YmZjMGM1NmM4Y2Q2N2FiYmE5Yw==
  dependencies: []
- name: gra-log-purger
  version: c8bc8915c96549b69ec39d468bf93f386cdda62c
  sha1: !binary |-
    NjNhNjQ1ZTgxMTc3NzJmNzY2MWE5NmNmYzY1NmIwOGEzODZlM2QyZQ==
  fingerprint: !binary |-
    YzhiYzg5MTVjOTY1NDliNjllYzM5ZDQ2OGJmOTNmMzg2Y2RkYTYyYw==
  dependencies:
  - golang
- name: haproxy
  version: !binary |-
    NzY2ZjlhNjExMDMxODY5NDE0ZTlhNDliNzcyN2RmMmMwY2I0ZjQyMA==
  sha1: !binary |-
    Y2QzNzVkNjljZTE4ZTM2YjZhN2U1NGI5NmVlYzQ0MTdjYjU5ODZiOA==
  fingerprint: !binary |-
    NzY2ZjlhNjExMDMxODY5NDE0ZTlhNDliNzcyN2RmMmMwY2I0ZjQyMA==
  dependencies: []
- name: mariadb
  version: e697fe25f98ce9cf9226d453dd22e9c636010abd
  sha1: !binary |-
    OTA2ZGNhYWUwMDE2NGU4ZjNlNWY1NWZkODliYzIyMGM4NDU5ODU4Zg==
  fingerprint: !binary |-
    ZTY5N2ZlMjVmOThjZTljZjkyMjZkNDUzZGQyMmU5YzYzNjAxMGFiZA==
  dependencies:
  - galera
- name: mariadb_ctrl
  version: c69aad0a8deca02279b440df167f0ca8d77c2349
  sha1: !binary |-
    ZGU1ODdiY2Q5ZDA4NDk4YzgxNDNjYWRjZDZlMDU4ZjE5YzQxNDhlNw==
  fingerprint: !binary |-
    YzY5YWFkMGE4ZGVjYTAyMjc5YjQ0MGRmMTY3ZjBjYThkNzdjMjM0OQ==
  dependencies:
  - golang
- name: mysql
  version: !binary |-
    OWYxYmFmOTdiMjBjYjAxOTNkMmI3ZjA1YzY0MzkzMTdkNDZlYWQ4NA==
  sha1: !binary |-
    Njc4Y2E4MGMzNDU2YjdiNTY4YWFjYzVjMmQ1OTliYjMzYjM2NDBjZg==
  fingerprint: !binary |-
    OWYxYmFmOTdiMjBjYjAxOTNkMmI3ZjA1YzY0MzkzMTdkNDZlYWQ4NA==
  dependencies: []
- name: mysqlclient
  version: !binary |-
    NDYzNTY5NTA0YTk1N2U0MWVkZGQ4MzEyM2JmZjEyY2M0MThjYmI1NA==
  sha1: !binary |-
    Y2VmNTMyZTU5NTc1NDM0NmFmODBkZGViNzRiZGYwNGVhOTBiNjk4OA==
  fingerprint: !binary |-
    NDYzNTY5NTA0YTk1N2U0MWVkZGQ4MzEyM2JmZjEyY2M0MThjYmI1NA==
  dependencies: []
- name: route-registrar
  version: !binary |-
    NjljMWI0NjMwNDZjNGIxZmU0NGM2NzliMTM0YTA5ZGJmNWEzYjQ2MA==
  sha1: !binary |-
    NDhiZDcyMTg0YmMzY2M5MGZmYmEzMDAxZjNlODE0NGE1YThkOGZlNA==
  fingerprint: !binary |-
    NjljMWI0NjMwNDZjNGIxZmU0NGM2NzliMTM0YTA5ZGJmNWEzYjQ2MA==
  dependencies:
  - golang
- name: ruby
  version: !binary |-
    Y2Q0ZDg0OTRhMTM3ZTIyOGU2MzU4ZWIxOGVlZTc1MjhlMzcxYTBhMA==
  sha1: !binary |-
    MTlmNmFlNzNhNjU0YWYzNTIyZTBiZjk1NmEyOWU5ZWI0ODY4NDU5OQ==
  fingerprint: !binary |-
    Y2Q0ZDg0OTRhMTM3ZTIyOGU2MzU4ZWIxOGVlZTc1MjhlMzcxYTBhMA==
  dependencies: []
- name: scons
  version: !binary |-
    MWRlYzMzNWUzZTgzZDExMTU2MjA0ZjdhM2NkY2M0NTJkOGEzZmZmZQ==
  sha1: !binary |-
    OTc1YTEwNTUwZDI0MjA3MmM0MWY1NGQzZmM3ZmI3Y2ZjMmZhMWY4NQ==
  fingerprint: !binary |-
    MWRlYzMzNWUzZTgzZDExMTU2MjA0ZjdhM2NkY2M0NTJkOGEzZmZmZQ==
  dependencies: []
- name: syslog_aggregator
  version: !binary |-
    MDc4ZGE2ZGNiOTk5YzFlNmY1Mzk4YTZlYjczOTE4MmNjYjRhYmEyNQ==
  sha1: !binary |-
    NGIwMmZlZWEzOTA1MDc0MmIzMGE0ODdjMzJkZWJjMzNmYmIzNDFhMw==
  fingerprint: !binary |-
    MDc4ZGE2ZGNiOTk5YzFlNmY1Mzk4YTZlYjczOTE4MmNjYjRhYmEyNQ==
  dependencies: []
jobs:
- name: acceptance-tests
  version: 9bc9c786217d902a4f06969a514a6653a77db1e5
  fingerprint: !binary |-
    OWJjOWM3ODYyMTdkOTAyYTRmMDY5NjlhNTE0YTY2NTNhNzdkYjFlNQ==
  sha1: !binary |-
    MmYyNWJmMjE5ODQ1NzM3NWNkOWQ3OTQzZjY5MGRjMzFlZWQyZDk0OA==
- name: broker-deregistrar
  version: !binary |-
    NmNkYmYyNjI0NmQxOGI0Y2RhYmUyNjBkZGFkZGNlN2FhNWIxNTE3YQ==
  fingerprint: !binary |-
    NmNkYmYyNjI0NmQxOGI0Y2RhYmUyNjBkZGFkZGNlN2FhNWIxNTE3YQ==
  sha1: !binary |-
    NDFjY2IyZmYzYzhmZjk0ZTEyYjI3ZmZhNDYxYzkxNGUzYWJkNTAxYw==
- name: broker-registrar
  version: !binary |-
    ODU0ZTkzNTA3ZWE1ZGIwZGZjZGI3NDYyODBjMzczMWJlMmNiYjYwNw==
  fingerprint: !binary |-
    ODU0ZTkzNTA3ZWE1ZGIwZGZjZGI3NDYyODBjMzczMWJlMmNiYjYwNw==
  sha1: !binary |-
    NTAyOTU5MDI4MGI0ZDhmM2FhYWQzOGRiNDYwYTA5NWVhZTA5OTEyZQ==
- name: cf-mysql-broker
  version: 8534c2b34524c7a53710e94cd9606b3c9046397d
  fingerprint: !binary |-
    ODUzNGMyYjM0NTI0YzdhNTM3MTBlOTRjZDk2MDZiM2M5MDQ2Mzk3ZA==
  sha1: !binary |-
    MmE4MDFkNWYwNmRhNDNhYTg2NDk0MzQ0YmIyMjExZmEzYWYxOWJmZQ==
- name: haproxy
  version: 6d6bd96aaa98776e110483ecbada2b5ad4eeb534
  fingerprint: !binary |-
    NmQ2YmQ5NmFhYTk4Nzc2ZTExMDQ4M2VjYmFkYTJiNWFkNGVlYjUzNA==
  sha1: !binary |-
    OWRhMjU2MDlkMTBlZWZhMGE2NzM0NzZlNTlhOTE3MDBhNzg5Mzg5Mg==
- name: mysql
  version: 0969781099629183091766b01d1356e0fd4a6115
  fingerprint: !binary |-
    MDk2OTc4MTA5OTYyOTE4MzA5MTc2NmIwMWQxMzU2ZTBmZDRhNjExNQ==
  sha1: !binary |-
    OTY0ODVlOTU5ZGMyZTNiYzFjZjNjYTNlNmVmZWY3MGE2OWI4OTc0Nw==
commit_hash: d623b839
uncommitted_changes: true
name: cf-mysql
version: '13'
