---
meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

  stemcell:
    name: bosh-stemcell
    version: latest


name: (( meta.environment "-mysql" ))
director_uuid: (( merge ))

releases:
- name: cf-mysql
  version: latest

compilation:
  workers: 3
  network: services1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: (( merge ))

resource_pools:
  - name: services-small
    network: services1
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

jobs:
  - name: mysql
    release: cf-mysql
    template:
    - mysql
    instances: 1
    resource_pool: services-small
    persistent_disk: 100000
    networks:
    - name: services1
      static_ips: (( static_ips(0) ))
    properties:
      admin_password: (( merge ))
      max_connections: 1500
      max_user_connections: 40

  - name: cf-mysql-broker
    release: cf-mysql
    template:
      - cf-mysql-broker
    instances: 1
    resource_pool: services-small
    networks:
    - name: services1
    properties:
      auth_password: (( merge ))
      services:
      - id: cf-mysql-1
        name: cf-mysql
        description: Cloud Foundry MySQL
        tags:
          - mysql
          - relational
        max_db_per_node: 255
        metadata:
          listing:
            imageUrl:
            blurb: MySQL service for application development and testing
        plans:
        - id: cf-mysql-plan-1
          name: free
          description: Free Trial
          max_storage_mb: 10
          metadata:
            cost: 0
            bullets:
              - content: Shared MySQL server
              - content: 100 MB storage
              - content: 40 concurrent connections
      mysql_node:
        host: (( jobs.mysql.networks.services1.static_ips.[0] ))
        admin_password: (( jobs.mysql.properties.admin_password ))

properties: {}  # Pivotal CF cannot generate global properties
