---
meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

  external_domain: (( merge ))
  nats: (( merge ))

name: (( meta.environment "-mysql" ))
director_uuid: (( merge ))

releases:
- name: cf-mysql
  version: latest

compilation:
  workers: 3
  network: services1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: (( merge ))

resource_pools:
  - name: services-small
    network: services1
    size: (( auto ))
    stemcell:
      name: (( merge ))
      # Always use the same version
      version: 2200
    cloud_properties: (( merge ))

jobs:
  - name: mysql
    release: cf-mysql
    template:
    - mysql
    instances: 1
    resource_pool: services-small
    persistent_disk: 100000
    networks:
    - name: services1
      static_ips: (( static_ips(0) ))
    properties:
      admin_password: (( merge ))
      max_connections: 1500
      max_user_connections: 40

  - name: cf-mysql-broker
    release: cf-mysql
    template:
      - cf-mysql-broker
    instances: 1
    resource_pool: services-small
    networks:
    - name: services1
    properties:
      auth_username: (( merge ))
      auth_password: (( merge ))
      cookie_secret: (( merge ))
      external_host: (( "p-mysql." meta.external_domain ))
      cc_api_uri: (( merge ))
      nats: (( meta.nats ))
      networks:
        broker_network: services1
      services:
      - name: p-mysql
        id: 44b26033-1f54-4087-b7bc-da9652c2a539
        description: MySQL service for application development and testing
        tags:
          - mysql
          - relational
        max_db_per_node: 250
        metadata:
          displayName: "Pivotal MySQL Dev"
          imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAABMCAYAAADJEu0BAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyNpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuNS1jMDE0IDc5LjE1MTQ4MSwgMjAxMy8wMy8xMy0xMjowOToxNSAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENDIChNYWNpbnRvc2gpIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjBDOTlBMkE3NDQ3MDExRTNCN0I5RDc0MjE2NTBCMjgzIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjBDOTlBMkE4NDQ3MDExRTNCN0I5RDc0MjE2NTBCMjgzIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MEM5OUEyQTU0NDcwMTFFM0I3QjlENzQyMTY1MEIyODMiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MEM5OUEyQTY0NDcwMTFFM0I3QjlENzQyMTY1MEIyODMiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz7RmE0vAAAGn0lEQVR42uycTYgjRRTH38heFNTJiFdlO3rx2nMQQXbADAwePAg94ElByJxW0Eui4HmSo3OQ3RZkERFMHwTxIpODtznMNLuuKIim/dZZD7b4wXrZjZ3wauZtWZ2uTqfjJP3/QTGTTnem+tW/Xr33uiYr1L44pBIZ7u6tEAAlcxdMACBkACBkACBkACBksHycyzrh9ae2aO3ue05exzdv0sEP39L+118S3b4NC4LFEPKL64/Tw6tr/zn+6fHPtPH2m/T7n3/AiuDsC1mxdeUS3fj7L3ro/lV6+YkLtOE8Sm9sPUPPB+/CimBxYuTrvx7TtR+/pw8/v07Pvv/O+NiT5+uwIECyB8DcQ4sRq/feR4898CC9dqExfv1J9BUsCBZPyB889wJtnH9k/PthEma88vFHsCBYPCG/dXhAvc+u0rVffqKD774hGg5hQbB4Qn7v6iEsBpDsAQAhA1AktPjixvH4sfQ/t27BWmBxhfz0lUuwEkBoAQCEDACEDCBkACBkAObPyhCPmQE8MgAQMgAQMgAQMli+ZI/aF0c/vaS5SYuT1s1xvbpuRLtgX2pJayZt9O8njjgeJK3PbRINbp523OfPiDKub3Efit6H+hydmPsQzHIAh7t7ULEQck8IYNNCNIqBEF2Rb910uQ8OD3gsxK1EEXLfYsMEuCz6H2nv1YSg24br9Xsp+u2hA20imgTd575EEPJsQwtXHGtaXtsQwivqifeFNxx9iUad2xqLN+D3Y8ME2GcRB3xuXbt+mydBU/ydebBtaF2+h1F/j3LYGmQgd79FbOSG5bVqEPqG5TwPTSFiU1ijwopaiid2J1yrQpOAz1ViXp+DbYOUY23uR4f7VMsZzgGLZE95vpalR+7PYHlsTBh4fUnWY1GXRWAjhB3+G67l/ZWJL8KklsUq4RR0FpUUMll4ZWV8Uyzds4gTG3xOS4uH8yaGcc7krJszfCqTkPtTY+9sosN2GrBdh/zzxFYrr77US9ogaan2Tt5r8DmtqghZZdUNLW42CVGvcDhigLI8iMfnRHw+iWXWtlpSm6ICEPLkc3KEUGUiY2Z9oh6Jia5WnUDE17Up7V0JIZPwst6ECkPDICJXLJtxhtfzxKTp8mC4YvBslloSkyCvmCljos6TmO9X9kfG/uv8s80JY5vvv5XD3qPxioa7e0GVhOyzyLwpY9o4w+up5M4Xxzb5tcPL6W+clKWJ2k2Jm22Ipghl5pEUOuLePDHJ08Kj8fgk4jyxdxI6eIawosmf7VchRnYMxk1brppiiZ6UzKTFop5hIsScjNXZ44Q8CToiljZ55Gk94FnGs0h+I20i+hNWUdtkeuk8srxpz2AUx8IofSHGmiZAFZZEKQPU5eW0LgZIlaqoQEgxi0lQBk6KkGWip7c7auqJVz6xd+KBZSKonFGQnBNVUcghN08zdDPH7A5EdUEfJJsnhxF76XX+vSm8S1hAlM4MJkMZQg4ybCmbbwgVitp7KYWc5pXz1I59Q0aukrw88Zo8XxfyNLVVVXE5C0uty80kNPmEsm1oXYvx8jjJ86ssZF2IrZwlL5WEuFqbRkBRSuji5hRziz3gWfFQLYPHDLVJawWHDuMHPklIMW4F7L1UQtaFqDyZnyP2lElInrAk7bNjQ/besaxAqCd6eR+ilIXa6BRq3jWckCjbVkCalkljJYRMWrLVSDHKpCdzfRFrN8Rr3Su1LAXoa4PWZZHvU/YDAbkx6f9MfEYiOxLVn03t/a6wWZpdaiZ7c504otPtrP3kWFgFIZ/LKM/0hWHSzoksvERH86K6yFweWCX0WCyvnhCgXjpTx0af36PTDUaR8ORyr/WORXw+sKjI7FjYdpCxak3aVrrDE6/DfQ/ptOSmwql2yr34GfZeWiFnLcvKMFm14ywhpyV5m+x5vJTlNOSBTfMs6tHtZTrdXG8S3zbZ1ZCzKiG2satjWLkiUXWY5ABCrtZ02C5eSlVpkr3jKiR5CrWxvuzM/IgHb8di8F1twPKEATVNaMrT10Qsumgxo35Pfbqzhkwg5zfWF4gJiexKblHB+FUvq6k4usX96C2goGOqSMJWZrI3C7yMpXAeQlCbb9R+5B6vEgBCtiJv7blMIo6T62T3z6igwqGFJ+JaVT6Kzlj2rAQNIOSJ8XBDW9YhGrBwQvbptJjfZ0+MJRyUDr6NEyDZAwBCBgBCBgBCBhAyABAyABAyABAygJABgJABgJABgJABhAwAhAwAhAwAhAwgZAAgZAAgZAAgZAAgZLBc/CvAALNW7XVv+EUjAAAAAElFTkSuQmCC"
          longDescription: "A MySQL relational database service for development and testing. The MySQL server is multi-tenant and is not replicated."
          providerDisplayName: "Pivotal Software"
          documentationUrl:
          supportUrl: "http://support.cloudfoundry.com/"
        dashboard_client:
            id: p-mysql
            secret: (( merge ))
            redirect_uri: (( "http://" external_host "/manage/auth/cloudfoundry/callback" ))
        plans:
        - name: 100mb
          id: ab08f1bc-e6fc-4b56-a767-ee0fea6e3f20
          description: Shared MySQL Server, 100MB persistent disk, 40 max concurrent connections
          max_storage_mb: 100
          metadata:
            costs:
            - amount:
                usd: 0.0
              unit: MONTHLY

            bullets:
              - Shared MySQL server
              - 100 MB storage
              - 40 concurrent connections
      mysql_node:
        host: (( jobs.mysql.networks.services1.static_ips.[0] ))
        admin_password: (( jobs.mysql.properties.admin_password ))
  - name: broker-registrar
    template: broker-registrar
    release: cf-mysql
    instances: 1
    resource_pool: services-small
    lifecycle: errand
    networks:
    - name: services1
    properties:
      cf:
        api_url: (( jobs.cf-mysql-broker.properties.cc_api_uri ))
        admin_username: (( merge ))
        admin_password: (( merge ))
      broker:
        name: p-mysql
        host: (( jobs.cf-mysql-broker.properties.external_host ))
        username: (( jobs.cf-mysql-broker.properties.auth_username ))
        password: (( jobs.cf-mysql-broker.properties.auth_password ))

properties: {}  # Pivotal CF cannot generate global properties
