---
meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

  stemcell:
    name: (( merge ))
    version: latest

name: (( meta.environment "-mysql" ))
director_uuid: (( merge ))

releases:
- name: cf-mysql
  version: latest

compilation:
  workers: 3
  network: services1
  reuse_compilation_vms: true
  cloud_properties: (( merge ))

update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 4

networks: (( merge ))

resource_pools:
  - name: services-small
    network: services1
    size: (( auto ))
    stemcell: (( meta.stemcell ))
    cloud_properties: (( merge ))

jobs:
  - name: mysql
    release: cf-mysql
    template:
    - mysql
    instances: 1
    resource_pool: services-small
    persistent_disk: 100000
    networks:
    - name: services1
      static_ips: (( static_ips(0) ))
    properties:
      admin_password: (( merge ))
      max_connections: 1500
      max_user_connections: 40

  - name: cf-mysql-broker
    release: cf-mysql
    template:
      - cf-mysql-broker
    instances: 1
    resource_pool: services-small
    networks:
    - name: services1
    properties:
      auth_username: (( merge ))
      auth_password: (( merge ))
      services:
      - name: p-mysql
        id: 44b26033-1f54-4087-b7bc-da9652c2a539
        description: MySQL service for application development and testing
        tags:
          - mysql
          - relational
        max_db_per_node: 250
        metadata:
          longDescription: A MySQL relational database service appropriate for development and testing. The service delivers databases on a multi-tenant non-redundant server. Unique user credentials are generated for each application binding.
          displayName: "Pivotal MySQL Dev"
          providerDisplayName: Pivotal
        plans:
        - name: 100mb
          id: ab08f1bc-e6fc-4b56-a767-ee0fea6e3f20
          description: Shared MySQL Server, 100mb persistent disk, 40 max concurrent connections
          max_storage_mb: 100
          metadata:
            costs:
            - amount:
                usd: 0.0
              unit: MONTHLY

            bullets:
              - Shared MySQL server
              - 5 MB storage
              - 40 concurrent connections
      mysql_node:
        host: (( jobs.mysql.networks.services1.static_ips.[0] ))
        admin_password: (( jobs.mysql.properties.admin_password ))

properties: {}  # Pivotal CF cannot generate global properties
