#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )
WORKSPACE_DIR="$( cd ${RELEASE_DIR}/.. && pwd )"

OK_COLOR='\033[1;32m'
ACTION_COLOR='\033[1;33m'
INFO_COLOR='\033[1;36m'
NO_COLOR='\033[0m'

CONFIG_LOCATION=${CONFIG_LOCATION:-${RELEASE_DIR}/integration-config.json}
echo -e "Creating config file at ${INFO_COLOR}${CONFIG_LOCATION}${NO_COLOR}..."

CF_API_USER="${CF_API_USER:?}"
CF_API_PASSWORD="${CF_API_PASSWORD:?}"
PROXY_API_USER="${PROXY_API_USER:?}"
PROXY_API_PASSWORD="${PROXY_API_PASSWORD:?}"
DOMAIN="${DOMAIN:-}"
if [ -z "${DOMAIN}" ]; then
  BOSH_LITE_PRIVATE_IP="$(cat ${WORKSPACE_DIR}/${BOSH_LITE_PRIVATE_IP_FILE:?} | jq -r '.private_ip')"
  DOMAIN="${BOSH_LITE_PRIVATE_IP}.xip.io"
fi
USE_SMALL_PLANS=${USE_SMALL_PLANS:-false}
USE_HTTPS=${USE_HTTPS:-true}

if [ "${USE_HTTPS}" = true ]; then
  PROTOCOL="https"
else
  PROTOCOL="http"
fi

if [ "${USE_SMALL_PLANS}" = true ]; then
  SMALL_PLAN_SIZE=10
  LARGE_PLAN_SIZE=20
else
  SMALL_PLAN_SIZE=100
  LARGE_PLAN_SIZE=1000
fi

PROXY_COUNT=${PROXY_COUNT:-2}
if [ "${PROXY_COUNT}" == 0 ]; then
  DASHBOARD_URLS="[]"
elif [ "${PROXY_COUNT}" == 1 ]; then
  DASHBOARD_URLS="[\"https://proxy-0.p-mysql.${DOMAIN}\"]"
else
  DASHBOARD_URLS="[\"https://proxy-0.p-mysql.${DOMAIN}\", \"https://proxy-1.p-mysql.${DOMAIN}\"]"
fi

# The following properties are only used by the failover test
BROKER_0_REMOTE_IP=${BROKER_0_REMOTE_IP:-}
BROKER_1_REMOTE_IP=${BROKER_1_REMOTE_IP:-}
MYSQL_NODE_0_REMOTE_IP=${MYSQL_NODE_0_REMOTE_IP:-}
BROKER_0_LOCAL_PORT=${BROKER_0_LOCAL_PORT:-}
BROKER_1_LOCAL_PORT=${BROKER_1_LOCAL_PORT:-}
MYSQL_NODE_0_LOCAL_PORT=${MYSQL_NODE_0_LOCAL_PORT:-}

cat > ${CONFIG_LOCATION} <<EOF
{
  "api": "${PROTOCOL}://api.${DOMAIN}",
  "apps_domain": "${DOMAIN}",
  "admin_user": "${CF_API_USER}",
  "admin_password": "${CF_API_PASSWORD}",
  "broker_host": "p-mysql.${DOMAIN}",
  "service_name": "p-mysql",
  "plans" : [
    {
      "plan_name": "100mb",
      "max_user_connections": 20,
      "max_storage_mb": ${SMALL_PLAN_SIZE}
    },
    {
      "plan_name": "1gb",
      "max_user_connections": 40,
      "max_storage_mb": ${LARGE_PLAN_SIZE}
    }
  ],
  "skip_ssl_validation": true,
  "timeout_scale": 1.0,
  "proxy": {
    "dashboard_urls": ${DASHBOARD_URLS},
    "api_username":"${PROXY_API_USER}",
    "api_password":"${PROXY_API_PASSWORD}",
    "api_force_https": ${USE_HTTPS},
    "skip_ssl_validation": true
  },
  "brokers": [
    {
      "ip": "${BROKER_0_REMOTE_IP}",
      "ssh_tunnel": "127.0.0.1:${BROKER_0_LOCAL_PORT}"
    },
    {
      "ip": "${BROKER_1_REMOTE_IP}",
      "ssh_tunnel": "127.0.0.1:${BROKER_1_LOCAL_PORT}"
    }
  ],
  "mysql_nodes": [
    {
      "ip": "${MYSQL_NODE_0_REMOTE_IP}",
      "ssh_tunnel": "127.0.0.1:${MYSQL_NODE_0_LOCAL_PORT}"
    }
  ]
}
EOF

echo -e "${OK_COLOR}OK${NO_COLOR}"

echo -e "
TIP: Export the environment variable with the following command:

${ACTION_COLOR}export CONFIG=${CONFIG_LOCATION}${NO_COLOR}"
