#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd $MY_DIR/.. && pwd )"

# This function expects to be called from the release directory.
function latest_release() {
  ls releases/cf-mysql-* | \
  cut -d '-' -f3         | \
  cut -d '.' -f1         | \
  sort -n                | \
  tail -1
}

pushd ${RELEASE_DIR}
  LATEST_RELEASE_VERSION=$( latest_release )
  cat << EOF > ${RELEASE_DIR}/cf-mysql-latest-version-stub.yml
---
releases:
- name: cf-mysql
  version: ${LATEST_RELEASE_VERSION}
EOF
popd
