#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

export BOSH_ENVIRONMENT="${BOSH_ENVIRONMENT:-https://192.168.50.4:25555}"
export BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:-cf-mysql}"

pushd "${RELEASE_DIR}" > /dev/null
  gobosh \
    deploy \
    "${RELEASE_DIR}/manifest-generation/cf-mysql-template-v2.yml" \
    -l "${RELEASE_DIR}/manifest-generation/bosh2.0/bosh-lite/default-vars.yml" \
    "$@"
popd > /dev/null
