#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

"${MY_DIR}/deploy-bosh-lite" \
  -o "${RELEASE_DIR}/manifest-generation/bosh2.0/overrides/add-broker.yml" \
  -o "${RELEASE_DIR}/manifest-generation/bosh2.0/overrides/register-proxy-route.yml" \
  "$@"
