#!/bin/bash

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"
MANIFEST_DIR="$( cd "${RELEASE_DIR}/manifest-generation" && pwd )"

argument_error=false

function usage(){
  >&2 echo " Usage:
  Mandatory arguments:   
    -c CF Manifest
    -p Property overrides stub file
    -i Infrastructure type stub file
  Optional arguments
    -n Instance count overrides stub file (single node, 3 node) 
    -v Release versions stub file
  "
  exit 1
}

while getopts "c:p:i:n:v:" opt; do
  case $opt in
    c)
      cf_manifest=$OPTARG
      ;;
    p)
      property_overrides=$OPTARG
      ;;
    i)
      infrastructure_type=$OPTARG
      ;;
    n)
      instance_counts=$OPTARG
      ;;
    v)
      release_versions=$OPTARG
      ;;
    *)
      echo "Unknown arguments"
      usage
      ;;
  esac
done

if [ -z "${infrastructure_type}" ]; then
  >&2 echo "infrastructure_type stub file is missing"
  argument_error=true
elif [ ! -f "${infrastructure_type}" ]; then
  >&2 echo "infrastructure_type stub ${infrastructure_type} is not a regular file"
  argument_error=true
fi

if [ -z "${cf_manifest}" ]; then
  >&2 echo "cf manifest file is missing"
  argument_error=true
elif [ ! -f "${cf_manifest}" ]; then
  >&2 echo "cf manifest ${cf_manifest} is not a regular file"
  argument_error=true
fi

if [ -z ${property_overrides} ]; then
  >&2 echo "property-overrides stub file is missing"
  argument_error=true
elif [ ! -f "${property_overrides}" ]; then
  >&2 echo "Property Overrides stub '${property_overrides}' is not a regular file"
  argument_error=true
fi

if [[ ! -z "${instance_counts}" && ! -f "${instance_counts}" ]]; then
  >&2 echo "Instance Count Overrides stub '${instance_counts}' is not a regular file"
  argument_error=true
fi

if [[ ! -z "${release_versions}" && ! -f "${release_versions}" ]]; then
  >&2 echo "Release versions stub '${release_versions}' is not a regular file"
  argument_error=true
fi

if [ "$argument_error" = "true" ]; then
  usage
fi

tmpdir=$(mktemp -d /tmp/mysql_manifest.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

spiff merge \
  ${MANIFEST_DIR}/misc-templates/config-from-cf.yml \
  ${MANIFEST_DIR}/misc-templates/config-from-cf-internal.yml \
  ${cf_manifest} \
  > ${tmpdir}/config-from-cf.yml

spiff merge \
  ${MANIFEST_DIR}/cf-mysql-template.yml \
  ${tmpdir}/config-from-cf.yml \
  ${infrastructure_type} \
  ${instance_counts} \
  ${property_overrides} \
  ${release_versions} \
  > ${tmpdir}/mysql-config.yml

spiff merge \
  ${MANIFEST_DIR}/misc-templates/bosh.yml \
  ${tmpdir}/mysql-config.yml
