#!/bin/bash

set -e

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

DIRECTOR_IP=${DIRECTOR_IP:-192.168.50.4}
BOSH_LITE_USERNAME=${BOSH_LITE_USERNAME:-admin}
BOSH_LITE_PASSWORD=${BOSH_LITE_PASSWORD:-admin}

tmpdir=$(mktemp -d /tmp/mysql_manifest.XXXXX)
trap '{ rm -rf ${tmpdir}; }' EXIT

argument_error=false

function usage(){
  >&2 echo " Usage:
  Optional arguments
    -j Job overrides stub file (e.g., for Consul)
    -n Instance count overrides stub file (single node, 3 node)
  "
  exit 1
}

pushd "${RELEASE_DIR}" > /dev/null

  bosh -n target "${DIRECTOR_IP}"
  bosh -n login "${BOSH_LITE_USERNAME}" "${BOSH_LITE_PASSWORD}"
  DIRECTOR_UUID="$(bosh status --uuid)"
  sed "s/REPLACE_WITH_DIRECTOR_UUID/$DIRECTOR_UUID/g" \
    "${RELEASE_DIR}/manifest-generation/bosh-lite-stubs/cf-manifest.yml" \
    > "${tmpdir}/bosh-lite-cf-manifest.yml"

  ./scripts/generate-deployment-manifest \
    -c "${tmpdir}/bosh-lite-cf-manifest.yml" \
    -p ./manifest-generation/bosh-lite-stubs/property-overrides.yml \
    -i ./manifest-generation/bosh-lite-stubs/iaas-settings.yml \
    "$@" \
    > cf-mysql.yml

  bosh deployment cf-mysql.yml
popd > /dev/null

echo "CF-MySQL Manifest was generated at ${RELEASE_DIR}/cf-mysql.yml"
