#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

DIRECTOR_IP=${DIRECTOR_IP:-192.168.50.4}
BOSH_LITE_USERNAME=${BOSH_LITE_USERNAME:-admin}
BOSH_LITE_PASSWORD=${BOSH_LITE_PASSWORD:-admin}

pushd "${RELEASE_DIR}" > /dev/null

  bosh -n target "${DIRECTOR_IP}"
  bosh -n login "${BOSH_LITE_USERNAME}" "${BOSH_LITE_PASSWORD}"

  tmpdir=$(mktemp -d /tmp/mysql_manifest.XXXXX)
  trap '{ rm -rf ${tmpdir}; }' EXIT

  bosh -n download manifest cf-warden "${tmpdir}/cf-warden.yml"

  ./scripts/generate-deployment-manifest \
    -c "${tmpdir}/cf-warden.yml" \
    -p ./manifest-generation/bosh-lite-stubs/property-overrides.yml \
    -i ./manifest-generation/bosh-lite-stubs/iaas-settings.yml \
    > cf-mysql.yml

  bosh deployment cf-mysql.yml
popd > /dev/null

echo "CF-MySQL Manifest was generated at ${RELEASE_DIR}/cf-mysql.yml"
