#!/usr/bin/env bash

set -eu

monit stop mariadb_ctrl

regex="[0-9]+$"

seq_no=$(cat /var/vcap/store/mysql/grastate.dat | grep 'seqno:')

if [ "$seq_no" = "seqno:   -1" ]; then
   /var/vcap/packages/mariadb/bin/mysqld --wsrep-recover
   seq_no=$(grep "Recovered position" /var/vcap/sys/log/mysql/mysql.err.log | tail -1)
fi

if [[ "$seq_no" =~ $regex ]]; then
  json_output="{\"sequence_number\":${BASH_REMATCH}}";
fi


echo $json_output

