#!/bin/bash

set -e -x

go get github.com/vito/gosub
go install github.com/vito/gosub

{
  gosub list \
    -test github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/... \
    -app  github.com/cloudfoundry/mariadb_ctrl/... \
    -test github.com/cloudfoundry/mariadb_ctrl/... \
    -app  github.com/cloudfoundry-incubator/galera-healthcheck/... \
    -test github.com/cloudfoundry-incubator/galera-healthcheck/... \
    -app  github.com/cloudfoundry-incubator/switchboard/... \
    -test github.com/cloudfoundry-incubator/switchboard/... \
    -app  github.com/pivotal-cf-experimental/cf-mysql-quota-enforcer/... \
    -test github.com/pivotal-cf-experimental/cf-mysql-quota-enforcer/... \

  # exclude these otherwise `gosub sync` will delete them
  echo gra-log-purger # not yet a submodule
  echo github.com/cloudfoundry-incubator/route-registrar # uses Godeps
  echo broker-registrar  # non-go project
  echo cf-mysql-broker   # non-go project
  echo common            # non-go project
  echo syslog_aggregator # non-go project
} | xargs gosub sync
