#!/usr/bin/env bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

source "${RELEASE_DIR}/.envrc"

# Remove and reinstall the ginkgo binary as it might be from the wrong target architecture
rm -rf "${RELEASE_DIR}/bin/ginkgo"
go install -v github.com/onsi/ginkgo/ginkgo
go get github.com/maxbrunsfeld/counterfeiter

# Start mysql to run integration tests against
mysqld_safe --character-set-server=utf8 --collation-server=utf8_unicode_ci &

echo -e "\n>>>>>>>> Testing MariaDB Control Integration..."
"${RELEASE_DIR}/src/github.com/cloudfoundry/mariadb_ctrl/bin/test-integration" "$@"

echo -e "\n>>>>>>>> Testing Quota Enforcer Integration..."
"${RELEASE_DIR}/src/quota-enforcer/bin/test-integration" "$@"
