#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd ${MY_DIR}/.. && pwd )

export PATH=$PATH:/usr/lib/chromium-browser/
export LD_LIBRARY_PATH=/usr/lib/chromium-browser/libs

CONFIG=${CONFIG:?}

source ${RELEASE_DIR}/.envrc

# Remove and reinstall the ginkgo binary as it might be from the wrong target architecture
rm -rf ${RELEASE_DIR}/bin/ginkgo
go install -v github.com/onsi/ginkgo/ginkgo

echo -e "\nTesting Dashboard SSO"
xvfb-run ${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/bin/test-dashboard "$@"
