#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd ${MY_DIR}/.. && pwd )"

${RELEASE_DIR}/generate_deployment_manifest \
    aws \
    ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
    ${RELEASE_DIR}/templates/sample_stubs/sample_aws_stub.yml

${RELEASE_DIR}/generate_deployment_manifest \
    vsphere \
    ${RELEASE_DIR}/templates/sample_stubs/sample_plans_stub.yml \
    ${RELEASE_DIR}/templates/sample_stubs/sample_vsphere_stub.yml
