#!/bin/bash

set -eu

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd "${MY_DIR}/.." && pwd )"

# shellcheck source=/dev/null
source "${RELEASE_DIR}/.envrc"

echo -e "\nTesting our bash scripts fatally..."
# Custom shellcheck exclusions
shellcheck --shell=bash "${RELEASE_DIR}/scripts/download-logs" -e SC2029 -e SC2068 -e SC2086

echo -e "\nTesting the rest of our bash scripts..."
# Things we have yet to address
pushd "${RELEASE_DIR}"
set +e
egrep -lR '#!/bin/bash|#!/usr/bin/env bash' scripts src | \
  egrep -v "(scripts/download-logs|scripts/test-unit|scripts/test-sample-stubs)" | \
  xargs shellcheck --shell=bash
set -e
popd

# Remove and reinstall the ginkgo binary as it might be from the wrong target architecture
rm -rf "${RELEASE_DIR}/bin/ginkgo"
go install -v github.com/onsi/ginkgo/ginkgo

echo -e "\nTesting Switchboard..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/switchboard/bin/test" "$@"

echo -e "\nTesting Galera Healthcheck..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/galera-healthcheck/bin/test" "$@"

echo -e "\nTesting MariaDB Control..."
"${RELEASE_DIR}/src/github.com/cloudfoundry/mariadb_ctrl/bin/test-unit" "$@"

echo -e "\nTesting Quota Enforcer..."
"${RELEASE_DIR}/src/github.com/pivotal-cf-experimental/cf-mysql-quota-enforcer/bin/test-unit" "$@"

echo -e "\nTesting Bootstrapper..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-bootstrap/bin/test" "$@"

echo -e "\nTesting Cluster Health Logger..."
"${RELEASE_DIR}/src/github.com/cloudfoundry-incubator/cf-mysql-cluster-health-logger/bin/test" "$@"
