#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live one directory below the release directory.
RELEASE_DIR=$( cd $MY_DIR/.. && pwd )

$RELEASE_DIR/src/github.com/cloudfoundry-incubator/switchboard/bin/test-ui

pushd $RELEASE_DIR
        go install github.com/onsi/ginkgo/ginkgo

        ginkgo -r -p -race -randomizeAllSpecs \
                src/github.com/cloudfoundry-incubator/switchboard \
                src/github.com/cloudfoundry-incubator/galera-healthcheck \
                src/github.com/cloudfoundry/mariadb_ctrl/
popd
