#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script assumes that it lives one directory below the release directory.
RELEASE_DIR="$( cd ${MY_DIR}/.. && pwd )"

FAKE_CF_MANIFEST="${RELEASE_DIR}/manifest-generation/bosh-lite-stubs/cf-manifest.yml"

# bosh-lite
${RELEASE_DIR}/scripts/generate-deployment-manifest \
    -c "${FAKE_CF_MANIFEST}" \
    -p "${RELEASE_DIR}"/manifest-generation/bosh-lite-stubs/property-overrides.yml \
    -i "${RELEASE_DIR}"/manifest-generation/bosh-lite-stubs/iaas-settings.yml

# minimal
${RELEASE_DIR}/scripts/generate-deployment-manifest \
    -c "${FAKE_CF_MANIFEST}" \
    -p "${RELEASE_DIR}"/manifest-generation/examples/property-overrides.yml \
    -i "${RELEASE_DIR}"/manifest-generation/bosh-lite-stubs/iaas-settings.yml \
    -n "${RELEASE_DIR}"/manifest-generation/examples/minimal/instance-count-overrides.yml
