#!/bin/bash
set -ux

function has_remote_branch() {
  git rev-parse @{u} > /dev/null 2>&1
}

set -e

has_remote_branch && git pull -r

git submodule foreach --recursive git submodule sync && git submodule update --init --recursive

git clean -ffd
