director_uuid: YOUR_DIRECTOR_UUID

networks:
  - name: services1
    type: manual
    subnets:
      - range: 10.10.32.0/20
        reserved:
          - 10.10.32.2 - 10.10.32.9
        static:
          - 10.10.32.10 - 10.10.32.255
        gateway: 10.10.32.1
        dns:
          - 10.10.0.2 # amazon has only 1 DNS server for the whole VPC at x.x.0.2
        cloud_properties:
          subnet: (( properties.template_only.aws.subnet_ids.services1 ))

properties:
  cf:
    # these come from your cf-release manifest
    admin_username: YOUR_CF_ADMIN_USERNAME
    admin_password: YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: false
    api_url: YOUR_CF_API_URI

  template_only:
    aws:
      availability_zone: YOUR_AWS_AVAILABILITY_ZONE #From the EC2 page of the AWS console, like us-east-1a
      subnet_ids:
        # From VPC/Subnets page of AWS console. Availability zone must match the value set above.
        services1: YOUR_SUBNET_ID

meta:
  environment: YOUR_ENVIRONMENT_NAME
  external_domain: YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-msyql.external_domain.
  apps_domain: YOUR_CF_APPS_DOMAIN
  nats:
    user: nats
    password: NATS_PASSWORD_FROM_CF_RELEASE
    machines:
      - 10.10.80.11
    port: 4222


jobs:
# Jobs for cf-mysql-release are below
- name: mysql
  properties:
    admin_password: A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process

- name: cf-mysql-broker
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: A_USERNAME_YOU_MAKE_UP # eg. cc
    auth_password: A_PASSWORD_YOU_MAKE_UP
    cc_api_uri: (( .properties.cf.api_url ))
    cookie_secret: A_PASSWORD_YOU_MAKE_UP
    services:
      - name: p-mysql
        dashboard_client:
          secret: A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
        plans:
        - name: YOUR_PLAN_NAME
          max_storage_mb: PLAN_SIZE_IN_MB
- name: haproxy
  release: cf-mysql
- name: broker-registrar
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
- name: broker-deregistrar
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
- name: acceptance-tests
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
      skip_ssl_validation: (( .properties.cf.skip_ssl_validation ))
