director_uuid: YOUR_DIRECTOR_UUID

networks:
- name: services1 # mysql release uses this network
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    reserved:
    - 10.0.0.2-10.0.0.109
    - 10.0.0.130-10.0.0.254
    static:
    - 10.0.0.120
    - 10.0.0.121
    - 10.0.0.122
    - 10.0.0.123
    - 10.0.0.124
    dns:
    - 10.0.0.3
    - 8.8.8.8
    cloud_properties:
      name: YOUR_SUBNET_NAME #This should match your vSphere network name, e.g. "VM Network".

properties:
  cf:
    api_url: https://api.YOUR_CF_SYSTEM_DOMAIN # full uri to the CF API (Cloud Controller), including scheme
    admin_username: YOUR_CF_ADMIN_USERNAME
    admin_password: YOUR_CF_ADMIN_PASSWORD
    skip_ssl_validation: true
  domain: YOUR_CF_SYSTEM_DOMAIN # The broker registers a route at p-mysql.external_domain
  app_domains:
  - YOUR_CF_APPS_DOMAIN
  nats:
    machines:
      - 10.0.0.5
    password: NATS_PASSWORD_FROM_CF_RELEASE
    user: nats
    port: 4222

meta:
  environment: YOUR_ENVIRONMENT_NAME

jobs:
- name: proxy
  properties:
    proxy:
      api_username: A_USERNAME_YOU_MAKE_UP # Used for basic auth in front of proxy api
      api_password: A_PASSWORD_YOU_MAKE_UP
- name: mysql
  properties:
    admin_password: A_PASSWORD_YOU_MAKE_UP #The admin password for the MySQL server process
- name: cf-mysql-broker
  properties:
    # The username & password cloud controller will use to authenticate with the service broker.
    auth_username: A_USERNAME_YOU_MAKE_UP #eg. cc
    auth_password: A_PASSWORD_YOU_MAKE_UP
    cc_api_uri: (( .properties.cf.api_url ))
    cookie_secret: A_PASSWORD_YOU_MAKE_UP
    services:
    - name: p-mysql
      dashboard_client:
        secret: A_PASSWORD_YOU_MAKE_UP #Secret used by MySQL dashboard to fetch an OAuth token from UAA
- name: broker-registrar
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
- name: broker-deregistrar
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
- name: acceptance-tests
  properties:
    cf:
      admin_username: (( .properties.cf.admin_username ))
      admin_password: (( .properties.cf.admin_password ))
      skip_ssl_validation: (( .properties.cf.skip_ssl_validation ))
